### ISSUE TITLE
Urgent: data in "Subject" and large text field "Adjective word or phrase" is not being retained when re-opened for edit

### ISSUE THREAD

**Issue by jpotvin** [RyanFleck/Xalgo-System-Prototype#17]
The data is retained only when first saved, but when I reopen an Input condition or Output assertion to re-edit it, the 'Subject' and 'Adjective word or phrase' of the large field are empty. 

Pls fix asap, as this will be needed for demo on Wed morning.

**Comment by RyanFleck** [comment]
Fixed.
