### ISSUE TITLE
Error 500 when attempting to reset password or set up new account

### ISSUE THREAD

**Issue by millenniallglyphs** [RyanFleck/Xalgo-System-Prototype#21]
When attempting to use the deployed rule maker, I get error 500 when attempting any action that requires email services.

<img width="1680" alt="Screen Shot 2020-12-28 at 12 30 21 PM" src="https://user-images.githubusercontent.com/27380420/103241943-859b1a80-4909-11eb-97bd-069f449331ef.png">

**Comment by RyanFleck** [comment]
Whoops. Thanks, Gmail.

I'll take a look tomorrow morning.

**Comment by RyanFleck** [comment]
Fixed.
